<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="0" ignored="5" total="10" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="EBay_Automation_Suite" duration-ms="229784" started-at="2020-07-23T12:41:25Z" finished-at="2020-07-23T12:45:14Z">
    <groups>
      <group name="SmokeTest">
        <method signature="LoginPageTest.assertLoginPageTitle()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@527740a2]" name="assertLoginPageTitle" class="com.ebay.automation.pagetests.LoginPageTest"/>
      </group> <!-- SmokeTest -->
      <group name="RegressionTest">
        <method signature="HomePageTest.openPurchaseHistory()[pri:0, instance:com.ebay.automation.pagetests.HomePageTest@6325a3ee]" name="openPurchaseHistory" class="com.ebay.automation.pagetests.HomePageTest"/>
        <method signature="LoginPageTest.login()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="login" class="com.ebay.automation.pagetests.LoginPageTest"/>
        <method signature="LoginPageTest.searchForProduct()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="searchForProduct" class="com.ebay.automation.pagetests.LoginPageTest"/>
        <method signature="LoginPageTest.signUp()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="signUp" class="com.ebay.automation.pagetests.LoginPageTest"/>
      </group> <!-- RegressionTest -->
    </groups>
    <test name="SmokeTests" duration-ms="90319" started-at="2020-07-23T12:41:25Z" finished-at="2020-07-23T12:42:55Z">
      <class name="com.ebay.automation.pagetests.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@527740a2]" name="setUp" is-config="true" duration-ms="909" started-at="2020-07-23T18:11:25Z" finished-at="2020-07-23T18:11:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="initialSetup(org.testng.ITestContext, java.lang.String, java.lang.String)[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@527740a2]" name="initialSetup" is-config="true" duration-ms="0" started-at="2020-07-23T18:11:26Z" finished-at="2020-07-23T18:11:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4d7c1f96]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.initialSetup]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.initialSetup
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Exception from WebDriverFactory.CreateDriver: [Ljava.lang.StackTraceElement;@7cf47cb4
	at com.ebay.automation.utils.WebDriverFactory.createDriver(WebDriverFactory.java:88)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:28)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method status="SKIP" signature="assertLoginPageTitle()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@527740a2]" name="assertLoginPageTitle" duration-ms="370" started-at="2020-07-23T18:12:54Z" finished-at="2020-07-23T18:12:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.initialSetup]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.initialSetup
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Exception from WebDriverFactory.CreateDriver: [Ljava.lang.StackTraceElement;@7cf47cb4
	at com.ebay.automation.utils.WebDriverFactory.createDriver(WebDriverFactory.java:88)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:28)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertLoginPageTitle -->
        <test-method status="FAIL" signature="afterClass()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@527740a2]" name="afterClass" is-config="true" duration-ms="0" started-at="2020-07-23T18:12:55Z" finished-at="2020-07-23T18:12:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.afterClass]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.afterClass
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.afterClass(TestBase.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.ebay.automation.base.TestBase.afterClass(TestBase.java:42)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.ebay.automation.pagetests.LoginPageTest -->
    </test> <!-- SmokeTests -->
    <test name="RegressionTests" duration-ms="229784" started-at="2020-07-23T12:41:25Z" finished-at="2020-07-23T12:45:14Z">
      <class name="com.ebay.automation.pagetests.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="setUp" is-config="true" duration-ms="917" started-at="2020-07-23T18:11:25Z" finished-at="2020-07-23T18:11:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="initialSetup(org.testng.ITestContext, java.lang.String, java.lang.String)[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="initialSetup" is-config="true" duration-ms="0" started-at="2020-07-23T18:11:26Z" finished-at="2020-07-23T18:11:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@66dabb42]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.initialSetup]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.initialSetup
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Exception from WebDriverFactory.CreateDriver: [Ljava.lang.StackTraceElement;@1c4e3c2
	at com.ebay.automation.utils.WebDriverFactory.createDriver(WebDriverFactory.java:88)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:28)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method status="SKIP" signature="login()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="login" duration-ms="368" started-at="2020-07-23T18:12:54Z" finished-at="2020-07-23T18:12:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.initialSetup]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.initialSetup
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Exception from WebDriverFactory.CreateDriver: [Ljava.lang.StackTraceElement;@1c4e3c2
	at com.ebay.automation.utils.WebDriverFactory.createDriver(WebDriverFactory.java:88)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:28)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="afterClass()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="afterClass" is-config="true" duration-ms="0" started-at="2020-07-23T18:12:55Z" finished-at="2020-07-23T18:12:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.afterClass]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.afterClass
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.afterClass(TestBase.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.ebay.automation.base.TestBase.afterClass(TestBase.java:42)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="initialSetup(org.testng.ITestContext, java.lang.String, java.lang.String)[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="initialSetup" is-config="true" duration-ms="59093" started-at="2020-07-23T18:12:55Z" finished-at="2020-07-23T18:13:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@66dabb42]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method status="SKIP" signature="searchForProduct()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="searchForProduct" duration-ms="2" started-at="2020-07-23T18:13:54Z" finished-at="2020-07-23T18:13:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.initialSetup]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.initialSetup
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Exception from WebDriverFactory.CreateDriver: [Ljava.lang.StackTraceElement;@1c4e3c2
	at com.ebay.automation.utils.WebDriverFactory.createDriver(WebDriverFactory.java:88)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:28)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchForProduct -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="afterClass" is-config="true" duration-ms="11636" started-at="2020-07-23T18:13:54Z" finished-at="2020-07-23T18:14:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="initialSetup(org.testng.ITestContext, java.lang.String, java.lang.String)[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="initialSetup" is-config="true" duration-ms="29276" started-at="2020-07-23T18:14:06Z" finished-at="2020-07-23T18:14:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@66dabb42]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method status="SKIP" signature="signUp()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="signUp" duration-ms="3" started-at="2020-07-23T18:14:35Z" finished-at="2020-07-23T18:14:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.initialSetup]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.initialSetup
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Exception from WebDriverFactory.CreateDriver: [Ljava.lang.StackTraceElement;@1c4e3c2
	at com.ebay.automation.utils.WebDriverFactory.createDriver(WebDriverFactory.java:88)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:28)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.ebay.automation.pagetests.LoginPageTest@3a5ed7a6]" name="afterClass" is-config="true" duration-ms="7162" started-at="2020-07-23T18:14:35Z" finished-at="2020-07-23T18:14:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.ebay.automation.pagetests.LoginPageTest -->
      <class name="com.ebay.automation.pagetests.HomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ebay.automation.pagetests.HomePageTest@6325a3ee]" name="setUp" is-config="true" duration-ms="97" started-at="2020-07-23T18:14:42Z" finished-at="2020-07-23T18:14:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="initialSetup(org.testng.ITestContext, java.lang.String, java.lang.String)[pri:0, instance:com.ebay.automation.pagetests.HomePageTest@6325a3ee]" name="initialSetup" is-config="true" duration-ms="27716" started-at="2020-07-23T18:14:42Z" finished-at="2020-07-23T18:15:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@66dabb42]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method status="SKIP" signature="openPurchaseHistory()[pri:0, instance:com.ebay.automation.pagetests.HomePageTest@6325a3ee]" name="openPurchaseHistory" duration-ms="1" started-at="2020-07-23T18:15:10Z" description="Opens Purchase History of the logged in user" finished-at="2020-07-23T18:15:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception from TestBase.initialSetup]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception from TestBase.initialSetup
	at org.testng.Assert.fail(Assert.java:83)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Exception from WebDriverFactory.CreateDriver: [Ljava.lang.StackTraceElement;@1c4e3c2
	at com.ebay.automation.utils.WebDriverFactory.createDriver(WebDriverFactory.java:88)
	at com.ebay.automation.base.TestBase.initialSetup(TestBase.java:28)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPurchaseHistory -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.ebay.automation.pagetests.HomePageTest@6325a3ee]" name="afterClass" is-config="true" duration-ms="4463" started-at="2020-07-23T18:15:10Z" finished-at="2020-07-23T18:15:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.ebay.automation.pagetests.HomePageTest -->
    </test> <!-- RegressionTests -->
  </suite> <!-- EBay_Automation_Suite -->
</testng-results>
